Module3 task1
htmlacademy-ecmascript/2130435-cinemaddict-19 pull request #5
Opened 2022-12-13 20:55 UTC by andy-rosa

2022-12-13 20:58 UTC, andy-rosa commented
Я прям чувствую, что напортачил. Много переделывал, глаз замылился. Скорее всего кривовато реализовал логику попапа фильма. В этих моментах нужно быть внимательнее), а то я уже не вижу ничего :(

2022-12-13 21:00 UTC, andy-rosa commented
И я вообще не чувствовал уверенность в назначение приватных, защищенных публичных свойств и назначении геттеров и сеттеров.

2022-12-16 12:00 UTC, Oleg979 requested changes

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/film-popup-details-info-view.js
> +const createGenreItem = (genres) => genres.map((genre) => `<span class="film-details__genre">${genre}</span>`).join('');
Название функции звучит так, как будто мы получаем разметку для одного жанра, а не для всех. Давай переименуем

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/film-card-control-button-view.js
> +  set active(newState = this._active) {
Уже обсуждали, что такая форма записи вообще не имеет смысла. Ну и потом, если переменная нужна снаружи и не содержит дополнительной логики - делать для неё геттер и сеттер смысла нет. Можно просто оставить публичной и обращаться по имени

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/film-card-control-button-view.js
> +  #getTemplate() {
А вот тут и в других вьюшках было бы полезно сделать get template(). Когда у нас есть функция без аргументов, довольно неплохо её записать покороче в виде геттера. Это не обязательно, просто хорошая практика

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/film-list-title-view.js
> +  get title() {
Тут тоже не вижу смысла в геттере и сеттере

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/film-list-title-view.js
> +  get show() {
И во всех подобных случаях

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/header-profile-view.js
> +  #rank = 'Movie Buff';
Давай тогда в модель вынесем, раз уж начали?

2022-12-16 12:00 UTC, Oleg979 commented on src/view/atom/header-profile-view.js
> +  get rank() {
Геттеры сеттеры не нужны

2022-12-16 12:00 UTC, Oleg979 commented on src/view/molecule/film-popup-comments-list-view.js
> +  get commentsLength() {
Идеальный пример геттера. Вот тут он нужен

2022-12-16 12:00 UTC, Oleg979 commented on src/view/organism/film-card-view.js
> +  get card() {
Тут в целом геттер допустим за счет сокращения названия

2022-12-16 12:00 UTC, Oleg979 commented on src/presenter/popup-presenter.js
> +  get film() {
Во всех этих случаях гет сет не нужны

2022-12-16 12:00 UTC, Oleg979 commented on src/presenter/popup-presenter.js
> +  renderPopup () {
Такой код не использует преимущества компонентного подхода и смотрится довольно странно на фоне всего остального. Предлагаю переписать, расскажу как

2022-12-22 12:37 UTC, merged