Module3 task2
htmlacademy-ecmascript/2130435-cinemaddict-19 pull request #6
Opened 2022-12-22 22:29 UTC by andy-rosa

2022-12-23 10:57 UTC, Oleg979 requested changes

2022-12-23 10:57 UTC, Oleg979 commented on src/view/wrapper/film-card-list-container-view.js
> +  isFilmsOver() {
можно упростить в одну строчку

2022-12-23 10:57 UTC, Oleg979 commented on src/view/wrapper/film-card-list-container-view.js
> +      if (this.#currentFilmsRange.length) {
Повторяет логику renderCurrentFilmCards

2022-12-23 10:57 UTC, Oleg979 commented on src/view/template/film-card-list-view.js
> +    button.addEventListener('click', () => {
Тут опять идет нарушение потока данных. Лучше передать в соответствующую вьюшку входной параметр - обработчик события клика

2022-12-26 05:28 UTC, andy-rosa commented
Вроде всё поправил как и обсудили, предлагаю красоту как раз навести в 4 разделе с фреймворком. Компоненты там вроде как сократятся, и уже будет видно лучше что где лишнее

2022-12-26 12:12 UTC, merged